// Progression milestones, shown as toasts.
export const ADVANCEMENTS = [
  { key: 'inventory', title: 'Taking Inventory', desc: 'Open your inventory', icon: 'book' },
  { key: 'wood', title: 'Getting Wood', desc: 'Punch a tree until a block of wood pops out', icon: 'oak_log' },
  { key: 'bench', title: 'Benchmarking', desc: 'Craft a crafting table', icon: 'crafting_table' },
  { key: 'pick', title: 'Time to Mine!', desc: 'Use planks and sticks to make a pickaxe', icon: 'wooden_pickaxe' },
  { key: 'stone', title: 'Stone Age', desc: 'Mine stone with your new pickaxe', icon: 'cobblestone' },
  { key: 'stonepick', title: 'Getting an Upgrade', desc: 'Construct a better pickaxe', icon: 'stone_pickaxe' },
  { key: 'torch', title: 'Light the Way', desc: 'Craft some torches', icon: 'torch' },
  { key: 'furnace', title: 'Hot Topic', desc: 'Construct a furnace out of cobblestone', icon: 'furnace' },
  { key: 'iron', title: 'Acquire Hardware', desc: 'Smelt an iron ingot', icon: 'iron_ingot' },
  { key: 'ironpick', title: "Isn't It Iron Pick", desc: 'Upgrade your pickaxe', icon: 'iron_pickaxe' },
  { key: 'armor', title: 'Suit Up', desc: 'Protect yourself with a piece of armour', icon: 'iron_chestplate' },
  { key: 'diamond', title: 'Diamonds!', desc: 'Acquire diamonds', icon: 'diamond' },
  { key: 'diamondpick', title: 'Shiny Tools', desc: 'Craft a diamond pickaxe', icon: 'diamond_pickaxe' },
  { key: 'obsidian', title: 'Ice Bucket Challenge', desc: 'Obtain a block of obsidian', icon: 'obsidian' },
  { key: 'hoe', title: 'Time to Farm!', desc: 'Till some soil with a hoe', icon: 'wooden_hoe' },
  { key: 'plant', title: 'A Seedy Place', desc: 'Plant a seed and watch it grow', icon: 'wheat_seeds' },
  { key: 'bread', title: 'Bake Bread', desc: 'Turn wheat into bread', icon: 'bread' },
  { key: 'cake', title: 'The Lie', desc: 'Bake a cake', icon: 'cake' },
  { key: 'eat', title: 'Delicious', desc: 'Eat something', icon: 'apple' },
  { key: 'bonemeal', title: 'Green Thumb', desc: 'Use bone meal on a plant', icon: 'bone_meal' },
  { key: 'hunter', title: 'Monster Hunter', desc: 'Kill any hostile monster', icon: 'iron_sword' },
  { key: 'creeper', title: 'Defused', desc: 'Defeat a creeper', icon: 'gunpowder' },
  { key: 'bow', title: 'Take Aim', desc: 'Shoot something with a bow', icon: 'bow' },
  { key: 'sniper', title: 'Sniper Duel', desc: 'Kill a skeleton with an arrow', icon: 'arrow' },
  { key: 'leather', title: 'Cow Tipper', desc: 'Harvest some leather', icon: 'leather' },
  { key: 'breed', title: 'Repopulation', desc: 'Breed two animals together', icon: 'wheat' },
  { key: 'tame', title: 'Best Friends Forever', desc: 'Tame a wolf with bones', icon: 'bone' },
  { key: 'sleep', title: 'Sweet Dreams', desc: 'Sleep in a bed to skip the night', icon: 'red_bed' },
  { key: 'bookshelf', title: 'Librarian', desc: 'Build a bookshelf', icon: 'bookshelf' },
  { key: 'dungeon', title: 'Dungeon Delver', desc: 'Open a chest in a monster dungeon', icon: 'mossy_cobblestone' },
  { key: 'table', title: 'Arcane Arts', desc: 'Construct an enchanting table', icon: 'enchanting_table' },
  { key: 'enchant', title: 'Enchanter', desc: 'Enchant an item at an enchanting table', icon: 'enchanted_book' },
  { key: 'anvil', title: 'Hammer Time', desc: 'Craft an anvil', icon: 'anvil' },
  { key: 'fish', title: 'Fishy Business', desc: 'Catch a fish', icon: 'fishing_rod' },
];
